services:
  app:
    image: ghcr.io/lpedrul/pedru-dev:latest
    container_name: pedru-dev-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    environment:
      - NODE_ENV=production
      - PRODUCTION=true
      - CERTBOT_EMAIL=dejesus.pedro2002@gmail.com
    networks:
      - web

  # Optional: Separate certbot service for certificate renewal
  certbot:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: renew --quiet
    profiles:
      - renewal
    networks:
      - web

volumes:
  letsencrypt:
  certbot-www:

networks:
  web:
    driver: bridge
