services:
  nginx-react:
    container_name: pedru-dev
    image: ghcr.io/lpedrul/pedru-dev:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      NODE_ENV: production
      PRODUCTION: "true"
      CERTBOT_EMAIL: "dejesus.pedro2002@gmail.com"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  letsencrypt:
  certbot-www: