name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pedru-dev:latest

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yaml,nginx/default.conf"
          target: "~/pedru-dev/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            cd ~/your-app
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pedru-dev:latest

            # Stop and remove old container
            docker-compose down || true

            # Start new container
            docker-compose up -d

            # Copy nginx config
            sudo cp nginx/default.conf /etc/nginx/sites-available/pedru.dev.br

            # Test nginx config
            sudo nginx -t

            # Reload nginx
            sudo systemctl reload nginx

            # Clean up old images
            docker image prune -f
